/*-----------------------------------------------------------------------------*/
/* Errors identifiers header file                                               */
/*                                                                             */
/* This file is automatically generated form excel sheet                       */
/*                                                                             */
/* Author: egarcia                                                             */
/*-----------------------------------------------------------------------------*/
#ifndef R100_ERRORS
#define R100_ERRORS

/******************************************************************************
** Includes
*/

#include "R100_Errors_cfg.h"

/******************************************************************************
** Defines
*/

#define OK                           eERR_NONE
#define DATA_NOT_AVAILABLE      -1   ///< Data is not available
#define APP_ERR_TRAP(a)     if (a) {/*__BKPT(0); */Lock_on_Panic();}

#define MAX_ERRORS               256               /// number of errors

/******************************************************************************
** Typedefs
*/

typedef enum
{
    eERR_NONE                                 = 0,   ///< OK condition: no error
    eERR_OPTION_DISABLED                      = 1,   ///< Option is disabled
    eERR_NV_SZ                                = 2,   ///< Error in non-volatile data
    /// free to use                           = 3,
    eERR_NFC_INFO                             = 4,   ///< NFC info is not available
    eERR_ZP_DATA                              = 5,   ///< ZP data are wrong. Calibration required
    eERR_AUDIO_MAX                            = 6,   ///< Minimum number of audio files is not correct
    /// free to use                           = 7,
    /// free to use                           = 8,
    /// free to use                           = 9,
    eERR_DEF_CHARGING_FAST                    = 10,   ///< The capacitor has charged very fast
    eERR_DEF_CHARGING_SLOW                    = 11,   ///< The capacitor has charged very slow
    eERR_DEF_DISCHARGING_H                    = 12,   ///< The CAP could not be discharged by the H hybrid
    eERR_DEF_DISCHARGING_R                    = 13,   ///< The CAP could not be discharged by the relay
    eERR_DEF_SHOCK                            = 14,   ///< Error during shock
    eERR_DEF_CURRENT_SENSE                    = 15,   ///< Error in capacitor current sense circuit
    /// free to use                           = 16,
    /// free to use                           = 17,
    /// free to use                           = 18,
    /// free to use                           = 19,
    eERR_ELECTRODE_EXPIRED                    = 20,   ///< Expired pads
    eERR_ELECTRODE_USED                       = 21,   ///< Used pads
    eERR_ELECTRODE_NOT_CONNECTED              = 22,   ///< No pads connected during the test
    eERR_ELECTRODE_WRONG                      = 23,   ///< Electrodes are incorrent
    /// free to use                           = 24,
    /// free to use                           = 25,
    /// free to use                           = 26,
    /// free to use                           = 27,
    /// free to use                           = 28,
    /// free to use                           = 29,
    eERR_BATTERY_EXPIRED                      = 30,   ///< Expired battery
    eERR_BATTERY_UNKNOWN                      = 31,   ///< Battery not identified
    eERR_BATTERY_LOW                          = 32,   ///< Low battery (<20%)
    eERR_BATTERY_REPLACE                      = 33,   ///< Replace battery (<10%)
    eERR_BATTERY_TEMP_OUT_RANGE               = 34,   ///< Battery temperature out of range
    eERR_BATTERY_TEMP_OUT_RANGE_OFF           = 35,   ///< Battery temperature out of range OFF device
    eRR_RTC                                   = 36,   ///< Battery RTC reading error
    /// free to use                           = 37,
    /// free to use                           = 38,
    /// free to use                           = 39,
    eERR_SMON_DCMAIN_TOO_HIGH                 = 40,   ///< Power supply is too high
    eERR_SMON_DCMAIN_TOO_LOW                  = 41,   ///< Power supply is too low
    eERR_SMON_18V_TOO_HIGH                    = 42,   ///< Capacitor power supply is too high
    eERR_SMON_18V_TOO_LOW                     = 43,   ///< Capacitor power supply is too low
    /// free to use                           = 44,
    /// free to use                           = 45,
    /// free to use                           = 46,
    /// free to use                           = 47,
    /// free to use                           = 48,
    /// free to use                           = 49,
    eERR_ADS_DEVICE_ID                        = 50,   ///< Error in state of ADS
    eERR_ADS_DEVICE_ACCESS                    = 51,   ///< Error in patient module
    eERR_ADS_CALIBRATION                      = 52,   ///< Device calibration error
    eERR_ADS_PAT_CONNECTED                    = 53,   ///< The patient is connected
    /// free to use                           = 54,
    /// free to use                           = 55,
    /// free to use                           = 56,
    /// free to use                           = 57,
    /// free to use                           = 58,
    /// free to use                           = 59,
    eERR_BOOT_PROCESSOR                       = 60,   ///< Bootloader processor is not responding
    eERR_BOOT_PROCESSOR_UPDATE                = 61,   ///< Error during the upgrade process
    eERR_BOOT_SPI_MEMORY                      = 62,   ///< Error in SPI memory
    /// free to use                           = 63,
    /// free to use                           = 64,
    /// free to use                           = 65,
    /// free to use                           = 66,
    /// free to use                           = 67,
    /// free to use                           = 68,
    /// free to use                           = 69,
    eERR_AUDIO_PLAYER                         = 70,   ///< Error in audio player
    eERR_AUDIO_QUEUE_FULL                     = 71,   ///< Concatenated queue is full
    /// free to use                           = 72,
    /// free to use                           = 73,
    /// free to use                           = 74,
    /// free to use                           = 75,
    /// free to use                           = 76,
    /// free to use                           = 77,
    /// free to use                           = 78,
    /// free to use                           = 79,
    eERR_COMM_UART_SELECT                     = 80,   ///< Error in the select of the UART for comms
    eERR_COMM_UART_BAUD_RATE                  = 81,   ///< Error in the UART baud rate setting
    eERR_COMM_UART_RX_ERROR                   = 82,   ///< Error in the UART data reception
    /// free to use                           = 83,
    /// free to use                           = 84,
    /// free to use                           = 85,
    /// free to use                           = 86,
    /// free to use                           = 87,
    /// free to use                           = 88,
    /// free to use                           = 89,
    /// free to use                           = 90,
    /// free to use                           = 91,
    /// free to use                           = 92,
    /// free to use                           = 93,
    /// free to use                           = 94,
    /// free to use                           = 95,
    /// free to use                           = 96,
    /// free to use                           = 97,
    /// free to use                           = 98,
    /// free to use                           = 99,
    eERR_COMM_WIFI_INIT                       = 100,   ///< Wi-Fi module initializing error
    eERR_COMM_WIFI_CHECK_STATUS               = 101,   ///< Wi-Fi module check status error
    eERR_COMM_WIFI_INIT_SYNC                  = 102,   ///< Wi-Fi module synchronization error
    eERR_COMM_WIFI_INIT_CONFIG_UART_DATA      = 103,   ///< Wi-Fi configuration UART data bits error
    eERR_COMM_WIFI_INIT_CONFIG_UART_BAUD      = 104,   ///< Wi-Fi configuration UART baud rate error
    eERR_COMM_WIFI_INIT_CONFIG_UART_FLOW      = 105,   ///< Wi-Fi configuration UART flow control error
    eERR_COMM_WIFI_INIT_CONFIG_UART_PARITY    = 106,   ///< Wi-Ficonfiguration UART parity error
    eERR_COMM_WIFI_INIT_CONFIG_UART_STOP      = 107,   ///< Wi-Fi configuration UART stop bits error
    eERR_COMM_WIFI_INIT_GET_MAC_ADDRESS       = 108,   ///< Wi-Fi module get MAC address error
    eERR_COMM_WIFI_INIT_GET_IP_ADDRESS        = 109,   ///< Wi-Fi module get IP address error
    eERR_COMM_WIFI_INIT_OPEN                  = 110,   ///< Wi-Fi module open comunication error
    eERR_COMM_WIFI_CERT_CLIENT_ROUTER         = 111,   ///< Wi-Fi client certficate configuration error
    eERR_COMM_WIFI_CERT_CLIENT_ROUTER_CA      = 112,   ///< Wi-Fi client CA certficate configuration error
    eERR_COMM_WIFI_CERT_CLIENT_ROUTER_KEY     = 113,   ///< Wi-Fi client key certficate configuration error
    eERR_COMM_WIFI_CERT_EAP_CONFIG            = 114,   ///< Wi-Fi EAP certficate configuration error
    eERR_COMM_WIFI_CERT_SERVER_TLS_CA         = 115,   ///< Wi-Fiserver TLS CA certficate configuration error
    eERR_COMM_WIFI_CERT_SERVER_TLS_CONFIG     = 116,   ///< Wi-Fi server TLS certficate configuration error
    eERR_COMM_WIFI_CERT_LIST                  = 117,   ///< Wi-Fi certficate listed error
    eERR_COMM_WIFI_CERT_RESET_STORE           = 118,   ///< Wi-Fi certficate storage error
    /// free to use                           = 119,
    eERR_COMM_WIFI_OPEN_TCP                   = 120,   ///< Wi-Fi TCP port opening error
    eERR_COMM_WIFI_CLOSE_TCP                  = 121,   ///< Wi-Fi TCP port closing error
    eERR_COMM_WIFI_OPEN_UDP                   = 122,   ///< Wi-Fi UDP port opening error
    eERR_COMM_WIFI_CLOSE_UDP                  = 123,   ///< Wi-Fi UDP port closing error
    eERR_COMM_WIFI_OPEN_UDP_SERVER            = 124,   ///< Wi-Fi UDP server port opening error
    eERR_COMM_WIFI_CLOSE_UDP_SERVER           = 125,   ///< Wi-Fi UDP server port closing error
    eERR_COMM_WIFI_OPEN_TLS                   = 126,   ///< Wi-Fi TLS port opening error
    eERR_COMM_WIFI_CLOSE_TLS                  = 127,   ///< Wi-Fi TLS port closing error
    /// free to use                           = 128,
    eERR_COMM_WIFI_SERVER_ALIVE               = 129,   ///< Wi-Fi server alive sending error
    eERR_COMM_WIFI_SEND_FRAME_TEST            = 130,   ///< Wi-Fi test data frame sending error
    eERR_COMM_WIFI_SEND_FRAME_ALERT           = 131,   ///< Wi-Fi alert data frame sending error
    eERR_COMM_WIFI_SEND_FRAME_GPS             = 132,   ///< Wi-Fi GPS data frame sending error
    eERR_COMM_WIFI_SEND_EPISODE               = 133,   ///< Wi-Fi episode file data sending error
    eERR_COMM_WIFI_SEND_TEST                  = 134,   ///< Wi-Fi test file data sending error
    eERR_COMM_WIFI_SEND_DATA                  = 135,   ///< Wi-Fi data sending error
    eERR_COMM_WIFI_RECEIVE_UPGRADE_FILE       = 136,   ///< Wi-Fi upgrade file receiving error
    eERR_COMM_WIFI_RECEIVE_CONFIG_FILE        = 137,   ///< Wi-Fi configuration file receiving error
    /// free to use                           = 138,
    eRR_COMM_WIFI_SERVER_RPS_ER               = 139,   ///< Wi-Fi server response ER error
    eERR_COMM_SIGFOX                          = 140,   ///< Sigfox comunication error
    eERR_COMM_SIGFOX_STATUS                   = 141,   ///< Sigfox check status error
    eERR_COMM_SIGFOX_MAX_POWER                = 142,   ///< Sigfox configation of trasmit max power error
    eERR_COMM_SIGFOX_RX                       = 143,   ///< Sigfox RX error
    eERR_COMM_SIGFOX_TEST_TX_FREQ             = 144,   ///< Sigfox TX frecuencies test error
    eERR_COMM_SIGFOX_TEST_RX_FREQ             = 145,   ///< Sigfox RX frecuencies test error
    eERR_COMM_SIGFOX_CW_TEST_START            = 146,   ///< Sigfox continuous wave test star error
    eERR_COMM_SIGFOX_CW_TEST_STOP             = 147,   ///< Sigfox continuous wave test stop error
    eERR_COMM_SIGFOX_RX_GFSK_TEST             = 148,   ///< Sigfox RX GFSK test error
    /// free to use                           = 149,
    eERR_COMM_GPS                             = 150,   ///< GPS module comunication error
    /// free to use                           = 151,
    /// free to use                           = 152,
    /// free to use                           = 153,
    /// free to use                           = 154,
    /// free to use                           = 155,
    /// free to use                           = 156,
    /// free to use                           = 157,
    /// free to use                           = 158,
    /// free to use                           = 159,
    eERR_COMM_ACC                             = 160,   ///< Acelerometer test error
    eERR_COMM_ACC_PRESENCE                    = 161,   ///< Acelerometer presence error
    eERR_COMM_ACC_CONFIGURATION               = 162,   ///< Acelerometer register configuration error
    eERR_COMM_ACC_INTERRUPT                   = 163,   ///< Error in the config of the interrupts of the acc
    /// free to use                           = 164,
    /// free to use                           = 165,
    /// free to use                           = 166,
    /// free to use                           = 167,
    /// free to use                           = 168,
    /// free to use                           = 169,
    /// free to use                           = 170,
    /// free to use                           = 171,
    /// free to use                           = 172,
    /// free to use                           = 173,
    /// free to use                           = 174,
    /// free to use                           = 175,
    /// free to use                           = 176,
    /// free to use                           = 177,
    /// free to use                           = 178,
    /// free to use                           = 179,
    eERR_KEYS                                 = 180,   ///< Error in keys
    eERR_LEDS                                 = 181,   ///< Error in leds
    /// free to use                           = 182,
    /// free to use                           = 183,
    /// free to use                           = 184,
    /// free to use                           = 185,
    /// free to use                           = 186,
    /// free to use                           = 187,
    /// free to use                           = 188,
    eRR_CRYPTO_AUTH                           = 189,   ///< Crypto authentication error
    eRR_EXPIRED_CERT_TLS                      = 190,   ///< TLS certificate expired
    eRR_EXPIRED_SOON_CERT_TLS                 = 191,   ///< TLS certificate expired soon
    eRR_EXPIRED_WPA_EAP                       = 192,   ///< WPA-EAP certificate expired
    eRR_EXPIRED_SOON_WPA_EAP                  = 193,   ///< WPA-EAP certificate expired soon
    /// free to use                           = 194,
    /// free to use                           = 195,
    /// free to use                           = 196,
    /// free to use                           = 197,
    /// free to use                           = 198,
    /// free to use                           = 199,
    /// free to use                           = 200,
    /// free to use                           = 201,
    /// free to use                           = 202,
    /// free to use                           = 203,
    /// free to use                           = 204,
    /// free to use                           = 205,
    /// free to use                           = 206,
    /// free to use                           = 207,
    /// free to use                           = 208,
    /// free to use                           = 209,
    /// free to use                           = 210,
    /// free to use                           = 211,
    /// free to use                           = 212,
    /// free to use                           = 213,
    /// free to use                           = 214,
    /// free to use                           = 215,
    /// free to use                           = 216,
    /// free to use                           = 217,
    /// free to use                           = 218,
    /// free to use                           = 219,
    /// free to use                           = 220,
    /// free to use                           = 221,
    /// free to use                           = 222,
    /// free to use                           = 223,
    /// free to use                           = 224,
    /// free to use                           = 225,
    /// free to use                           = 226,
    /// free to use                           = 227,
    /// free to use                           = 228,
    /// free to use                           = 229,
    /// free to use                           = 230,
    /// free to use                           = 231,
    /// free to use                           = 232,
    /// free to use                           = 233,
    /// free to use                           = 234,
    /// free to use                           = 235,
    /// free to use                           = 236,
    /// free to use                           = 237,
    /// free to use                           = 238,
    /// free to use                           = 239,
    /// free to use                           = 240,
    /// free to use                           = 241,
    /// free to use                           = 242,
    /// free to use                           = 243,
    /// free to use                           = 244,
    /// free to use                           = 245,
    /// free to use                           = 246,
    /// free to use                           = 247,
    /// free to use                           = 248,
    /// free to use                           = 249,
    /// free to use                           = 250,
    /// free to use                           = 251,
    /// free to use                           = 252,
    /// free to use                           = 253,
    /// free to use                           = 254,
    eERR_END                                  = MAX_ERRORS-1
} ERROR_ID_e;

#endif /* R100_ERRORS_H*/
/*-----------------------------------------------------------------------------*/
