/*-----------------------------------------------------------------------------*/
/* Errors configuration (destinations and actions) header file                 */
/*                                                                             */
/* This file is automatically generated form excel sheet                       */
/*                                                                             */
/* Author: egarcia                                                             */
/*-----------------------------------------------------------------------------*/
#ifndef R100_ERRORS_CFG_H
#define R100_ERRORS_CFG_H

#define MAX_ERRORS               256               /// Number of errors
/******************************************************************************
** Includes
*/

#include "R100_Errors.h"
#include "types_basic.h"              // Application types

/******************************************************************************
** Typedefs
*/

/// errors configuration structure
typedef struct {
    uint8_t   warning_error;     /// Warning (0) or error (1)
    uint8_t   user_indication;   /// User indication No (0) or Yes (1)
    uint8_t   daily_monthly;     /// Recoverable in daily (0) or monthly(1)
    uint8_t   led_flashing;      /// Led flashing No (0) or Yes (1)
    char_t    text[50];          /// Text identifier associated
}ERRORS_CFG_t;

/******************************************************************************
** Globals
*/

/// errors configuration table
extern const ERRORS_CFG_t R100_Errors_cfg[MAX_ERRORS];

#endif /* R100_ERRORS_CFG_H*/
/*-----------------------------------------------------------------------------*/
