name: CI for Renesas S3A7 with self-hosted runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Usa el runner autohospedado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install MinGW
      run: |
        choco install mingw -y

    - name: Install ARM Toolchain
      run: |
        choco install gcc-arm-embedded -y

    - name: Set environment variables
      run: |
        echo "PATH=$PATH;C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2020-q4-major\bin;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin" >> $GITHUB_ENV

    # Compilar usando e2studio
    - name: Compile firmware
      run: |
        cd "C:\Users\asier\OneDrive\Desktop\CUnit - Osatu\Apuntes\API\repo-github\R100_GitHub\REANIBEX_100_s3a7\Debug"
        mingw32-make -j8 all > compile_log.txt 2>&1      
        
    # Ejecutar el proyecto en la placa
    - name: Start GDB Server & Run project on board
      run: |
        Start-Process "JLinkGDBServer" -ArgumentList "-device R7FS3A77C", "-if SWD", "-speed 4000", "-port 61234", "-nogui" -NoNewWindow
        Start-Sleep -Seconds 2 # Esperar un momento para que el servidor GDB esté listo
        arm-none-eabi-gdb "C:\Users\asier\OneDrive\Desktop\CUnit - Osatu\Apuntes\API\repo-github\R100_GitHub\REANIBEX_100_s3a7\Debug\REANIBEX_100_s3a7.elf" -ex "handle SIGTRAP nostop pass" -ex "target remote localhost:61234" -ex "delete breakpoints" -ex "delete hwbreak" -ex "load" -ex "continue" 2>&1 | tee gdb_log.txt
