name: CI for Renesas S3A7 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up C/C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make

    - name: Build project
      run: |
        make -C C:\Users\asier\OneDrive\Desktop\CUnit - Osatu\Apuntes\API\repo-github\R100_GitHub\REANIBEX_100_s3a7\Debug> make all

    - name: Run Unit Tests
      run: |
        make -C C:\Users\asier\OneDrive\Desktop\CUnit - Osatu\Apuntes\API\repo-github\R100_GitHub\REANIBEX_100_s3a7\Debug> test
