name: CI for Renesas S3A7 with self-hosted runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Cambiar a Linux (Ubuntu)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make  # Instalar GCC y Make en Linux
        
    - name: List files
      run: |
        ls REANIBEX_100_s3a7/Debug  # Comando 'ls' en lugar de 'dir'
        
    # Compilar el código para la placa
    - name: Build firmware
      run: |
        cd "REANIBEX_100_s3a7/Debug"
        make -j8 all
