name: CI for Renesas S3A7 with self-hosted runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Usa el runner autohospedado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Compilar el código para la placa
    - name: Build firmware
      run: |
        mingw32-make -C "C:\Users\asier\OneDrive\Desktop\CUnit - Osatu\Apuntes\API\repo-github\R100_GitHub\REANIBEX_100_s3a7\Debug" -j8 all
