name: CI for Renesas S3A7 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up ARM GCC for Windows
      run: |
        choco install gcc-arm-embedded

    - name: Verify that all source files are present
      run: |
        ls REANIBEX_100_s3a7/synergy/ssp/src/framework/sf_spi/

    - name: Crear archivos .o
      run: |
        make -C "REANIBEX_100_s3a7/Debug" -j8 all

    - name: Build project
      run: |
        make -C "REANIBEX_100_s3a7/Debug" all
