name: CI for Renesas S3A7 with self-hosted runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Usa el runner autohospedado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install MinGW
      run: |
        choco install mingw -y

    - name: Install ARM Toolchain
      run: |
        choco install gcc-arm-embedded -y

    - name: Set environment variables
      run: |
        echo "PATH=$PATH;C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2020-q4-major\bin;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin" >> $GITHUB_ENV

    # Compilar usando e2studio
    - name: Build firmware with e2studio
      run: |
        "C:\Renesas\e2_studio\eclipse\eclipsec.exe" -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data "C:\Users\asier\OneDrive\Desktop\CUnit - Osatu\Apuntes\API\repo-github\R100_GitHub" -import "REANIBEX_100_s3a7" -cleanBuild all

    # Ejecutar el proyecto en la placa
    - name: Run project on board
      run: |
        "C:\Renesas\e2_studio\eclipse\eclipsec.exe" -nosplash -application org.eclipse.debug.core.DebugPlugin -launch "C:\Users\asier\OneDrive\Desktop\CUnit - Osatu\Apuntes\API\repo-github\R100_GitHub\REANIBEX_100_s3a7\REANIBEX_100_s3a7.elf.launch" -debug
