name: CI for Renesas S3A7 with self-hosted runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Usa el runner autohospedado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install MinGW
      run: |
        choco install mingw
        
    - name: Ruta actual
      run: |
        cd REANIBEX_100_s3a7\Debug
        
    # Compilar el código para la placa
    - name: Build firmware
      run: |
        mingw32-make -j8 all
